// The icon registry's name set, shared so callers get compile-time-checked glyphs
// (a typo fails svelte-check rather than rendering nothing).
export type IconName =
  | 'sun'
  | 'moon'
  | 'command'
  | 'search'
  | 'dashboard'
  | 'snippets'
  | 'sftp'
  | 'terminal'
  | 'splitRight'
  | 'splitDown'
  | 'serial'
  | 'close'
  | 'collapse'
  | 'expand'
  | 'check'
  | 'play'
  | 'edit'
  | 'copy'
  | 'trash'
  | 'plus'
  | 'folder'
  | 'file'
  | 'upload'
  | 'download'
  | 'refresh'
  | 'key'
  | 'shield'
  | 'settings'
  | 'telegram'
  | 'star'
  | 'tunnel'
  | 'chevronUp'
  | 'chevronDown';
